### ISSUE TITLE
Hover effects (mouse-over) or Annotations

### ISSUE THREAD

**Issue by vijib** [nitro-bio/sequence-viewers#74]
## Component Description
Hover effects (mouse-over) or Annotations.
Currently we have hover effect (mouse-over) or Annotations built already.  Works well except if the annotations is 1 wide aka between adjacent cells to do a hover how to implement ?
example
const annotations: Annotation[] = [
    {
      text: 'example',
      type: 'CDS',
      direction: 'forward',
      start: 10,
      end: 200,
      className:
        'dark:text-amber-800 dark:bg-amber-400 bg-amber-600 text-white',
    },
    {
      text: 'example',
      type: 'foo',
      direction: 'reverse',
      start: 300,
      end: 20,
      className: 'dark:text-rose-800 dark:bg-rose-400 bg-rose-600 text-white',
    },
  ]; 

works perfectly

const annotations: Annotation[] = [
    {
      text: 'example',
      type: 'CDS',
      direction: 'forward',
      start: 10,
      end: 10,
      className:
        'dark:text-amber-800 dark:bg-amber-400 bg-amber-600 text-white',
    },
    {
      text: 'example',
      type: 'foo',
      direction: 'reverse',
      start: 11,
      end: 11,
      className: 'dark:text-rose-800 dark:bg-rose-400 bg-rose-600 text-white',
    },
  ];

This effect of 10 hides 11. Is it possible to implement hover over and show a specialized text like Pos:10 and probably or even the hover effect or mouse over. Any way to show some extra context over each cell would be appreciated.
## Style Variants

- [x] Dark Mode
- [ ] Light Mode

**Comment by ninjha01** [comment]
I'm out until Jan 6th, but I'll definitely take a look then!

**Comment by ninjha01** [comment]
@vijib Don't think I fully understand, 
![CleanShot 2024-12-30 at 10 09 31](https://github.com/user-attachments/assets/e125f645-b056-4ee8-a7b3-317cdb44fb03)

Are you seeing something other than two annotations side by side, where you can hover over each individually?

Or are you asking to be able to override the builtin hover label with something else?

**Comment by vijib** [comment]
@ninjha01  Is there a way to do hover effects of adjacent cells. If so please share the code with me please ? Thanks

**Comment by ninjha01** [comment]
There isn't a way to hover an adjacent cell currently. Could you tell me a little about what it would enable for you?

[Here](https://github.com/nitro-bio/example_nitro_ui/blob/main/src/App.tsx#L52) is some example code with your example annotations

**Comment by vijib** [comment]
The example you have works beautifully. Would be grateful if you please tell me what this means
const annotations: Annotation[] = [
    {
      text: "example",
      type: "CDS",
      direction: "forward",
      start: 10,
      end: 10,
      className:
        "dark:text-amber-800 dark:bg-amber-400 bg-amber-600 text-white",
    },
    {
      text: "example",
      type: "foo",
      direction: "reverse",
      start: 11,
      end: 11,
      className: "dark:text-rose-800 dark:bg-rose-400 bg-rose-600 text-white",
    },
  ];

the className 
        "dark:text-amber-800 dark:bg-amber-400 bg-amber-600 text-white",
and 
 className: "dark:text-rose-800 dark:bg-rose-400 bg-rose-600 text-white", 
 what are they achieving? Thanks

**Comment by ninjha01** [comment]
That's using tailwind's [dark mode](https://tailwindcss.com/docs/dark-mode) to set specific styles when the `dark` className is set on a parent element. In that case you'll see the text be set to rose-800 and the background set to rose-400 like so:

<img width="374" alt="image" src="https://github.com/user-attachments/assets/de5bebdf-4945-4d55-bb97-1c149f0ff981" />
<img width="374" alt="image" src="https://github.com/user-attachments/assets/24f26d23-0261-4e72-9458-9b8444f386d2" />

as opposed to text in white and background in rose-600 like so

![CleanShot 2024-12-30 at 12 16 50@2x](https://github.com/user-attachments/assets/3f158c7f-93d4-46ef-bacb-da0e895d0738)
![CleanShot 2024-12-30 at 12 16 59@2x](https://github.com/user-attachments/assets/d426be66-13f9-4981-8f93-8e0452cfa5a4)

**Comment by vijib** [comment]
Aha, looks good. Thanks @ninjha01  please close this issue. thanks again for your help

**Comment by vijib** [comment]
sorry one more question. what is forward and reverse here ?

**Comment by ninjha01** [comment]
You sometimes want to show whether the CDS (or other annotation) is on the "forward" strand (5' to 3') or the reverse stand of DNA/RNA.

**Comment by vijib** [comment]
Got it. Thanks @ninjha01  Appreciate your help
