### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vijib** [nitro-bio/sequence-viewers#75]
What is the sequences parameter here for ?

<div className="flex max-h-[600px] overflow-y-auto">
      <SequenceViewer
        sequences={[
          "ATGC".repeat(100),
          " ".repeat(30) + "ATGC".repeat(20),
          " ".repeat(80) + "ATGC".repeat(70),
        ]}
        annotations={annotations}
        selection={selection}
        setSelection={setSelection}
        charClassName={charClassName}
        selectionClassName="relative after:bg-brand-400/20 after:absolute after:-left-px after:right-0 after:inset-y-0 after:z-[-1]"
        noValidate
      />
    </div>

The sequences parameter is an array. What is the individual items of this array and how is this represented ?

Suppose i want to show a list of sequences item1 in one color followed by item2  in same line in different color how would i do this ?

specifically inputs[SEQUENCE_STRING_KEY] and data?.sequence should be in same line but in different color ?

The following code returns green for both in one line. I want one line but different colors. Is that possible ?

                          <SequenceViewer
                            annotations={annotations}
                            charClassName={charClassName}
                            noValidate
                            selection={null}
                            sequences={[ (inputs[SEQUENCE_STRING_KEY], data?.sequence )|| '']}
                          />
                        </div>
thanks

**Comment by ninjha01** [comment]
If I understand you correctly, you want to achieve something like this, where the color of the sequence changes between certain indices.
![CleanShot 2024-12-30 at 21 18 28@2x](https://github.com/user-attachments/assets/4866c7fd-0d16-4c46-b756-3532a8fbc00a)

It's poorly documented, but you can use the `charClassName` function to achieve this like so:

```typescript
 const charClassName = ({
    base,
    sequenceIdx,
  }: {
    base: {
      base: string;
      index: number;
    };
    sequenceIdx: number;
  }) => {
    if (sequenceIdx === 0) {
      if (base.index >= 14 && base.index <= 80) {
        return "pt-2 dark:text-red-300 text-red-600";
      }
      return "pt-2 dark:text-brand-300 text-brand-600";
    } else if (sequenceIdx === 1) {
      return "dark:text-indigo-300 text-indigo-600";
    } else {
      return "dark:text-amber-300 text-amber-600";
    }
  };
```

I updated the example repo [here](https://github.com/nitro-bio/example_nitro_ui/blob/main/src/App.tsx#L77)

I'll make sure to update the documentation with this soon!

**Comment by vijib** [comment]
@ninjha01  Thank you so much!

Also is there a way to convert the hex code into the className color tailwind spec in the Annotation ?

  const annotations: Annotation[] = [
    {
      text: "example",
      type: "CDS",
      direction: "forward",
      start: 10,
      end: 10,
      className:
        "dark:text-amber-800 dark:bg-amber-400 bg-amber-600 text-white",
    },
    {
      text: "example",
      type: "foo",
      direction: "reverse",
      start: 11,
      end: 11,
      className: "dark:text-rose-800 dark:bg-rose-400 bg-rose-600 text-white",
    },
  ];

**Comment by ninjha01** [comment]
Yes - you can use something like this bg-[#50d71e] and text-[#50d71e]

https://tailwindcss.com/docs/background-color#arbitrary-values

The hex values will have to be hardcoded however

**Comment by vijib** [comment]
For example className:
        "dark:text-amber-800 dark:bg-amber-400 bg-amber-600 text-white",
        
what can I try ?

**Comment by ninjha01** [comment]
Are you set up to [use tailwind](https://tailwindcss.com/docs/installation/) in your project? If not, you'll have to define your own css classes like so:

in `index.css` or similar:
```
.sequence-green {
	/* text-green-500 */
	color: #6ee7b7;
}

.sequence-red {
	/* text-red-500 */
	color: #ef4444;
}
```


```
  const charClassName = ({
    base,
    sequenceIdx,
  }: {
    base: {
      base: string;
      index: number;
    };
    sequenceIdx: number;
  }) => {
    if (sequenceIdx === 0) {
      if (base.index >= 14 && base.index <= 80) {
        return "pt-2 sequence-red"; // use the className of the css above
      }
      return "pt-2 sequence-green";
    } else if (sequenceIdx === 1) {
      return "dark:text-indigo-300 text-indigo-600";
    } else {
      return "dark:text-amber-300 text-amber-600";
    }
  };
```

does this help?

**Comment by vijib** [comment]
my question is related to 
onst annotations: Annotation[] = [
{
text: "example",
type: "CDS",
direction: "forward",
start: 10,
end: 10,
className:
"dark:text-amber-800 dark:bg-amber-400 bg-amber-600 text-white",
},
{
text: "example",
type: "foo",
direction: "reverse",
start: 11,
end: 11,
className: "dark:text-rose-800 dark:bg-rose-400 bg-rose-600 text-white",
},
];

For example className:
"dark:text-amber-800 dark:bg-amber-400 bg-amber-600 text-white",

The text and bg are same in your above example. also is and valid syntax ?

className: "dark:bg-[#FFBF00] text-[#ff03]" is showing as black background.
what can I try ? please give me example with hex code and i can try. Thanks

**Comment by vijib** [comment]
I figured out a way to do this.  Thanks again for your help. Will close this issue
